sudo: required

language: generic

env:
  - DOCKER_COMPOSE_VERSION=1.14.0

services:
  - docker

install:
  # Installing docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # Get appropriate binaries...
  - curl -sSL https://goo.gl/6wtTN5 | bash -s 1.1.0
  - export PATH=`pwd`/bin:$PATH

before_script:
  # Check docker & docker-compose versions
  - docker --version
  - docker-compose --version

script:
  - cd network/docker
  - ./fabric.sh e2e